[build]
  command = "npm run build"
  publish = "dist"

[[headers]]
  for = "/search.json"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=2592000"

[[redirects]]
  from = "/rarity-guide"
  to = "/rarities"
  status = 301

[[redirects]]
  from = "/sets/jin-s2"
  to = "/sets/nrsa02"
  status = 301

[[redirects]]
  from = "/cards/jin-s2-*"
  to = "/cards/nrsa02-:splat"
  status = 301
